config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {sessions: 'sessions'}

  resources :badges, only: :index

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end    
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers_amount, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers_amount
    errors.add(:amount) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  TYPES_OF_BADGES = %i[all_by_category first_try all_by_level]

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image_url, :rule, presence: true
  validates :name, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', optional: true

  has_many :questions, dependent: :destroy

  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  
  scope :by_category, -> (title) {
   joins(:category)
   .where(categories: {title: title})
   .order(title: :desc) }

  def self.select_title(title)
    by_category(title).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions +=1 if correct_answer?(answer_ids)
    save!
  end

  def passed_by_percents
    ((correct_questions.to_f * 100) / test.questions.count).round(0)
  end

  def passed?
    passed_by_percents.to_i >= SUCCESS_RATIO
  end

  def left_time
    return if test.timer.nil?
    time = set_timer - Time.current
    return 0 if time <= 0
    time
  end

  def time_is_over?
    left_time == 0
  end

  private
  
  def set_timer
    created_at + test.timer.minute
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_current_question
    return unless test.present?
    self.current_question = 
      if current_question.nil?
        test.questions.first
      else
        next_question
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  def show_passed_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private
  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image_url, :rule, :option)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_badges = current_user.badges
    @badges = Badge.all
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create!(user: current_user, question: @test_passage.current_question, url: result.html_url, gist_id: result.id)
      flash[:notice] = t('.success', url: result.html_url)    
    else
      flash[:alert] = t('.failure')
    end
    redirect_to @test_passage
  end

  private
  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]
    
  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/alert_helper.rb
module AlertHelper

  def add_alert_message(key)
    case key.to_sym
      when :alert
        "alert-danger"
      when :warning
        "alert-warning"
      when :notice
        "alert-success"
      else
        "alert-info"
    end  
  end  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted? 
      "Edit #{question.test.title} question" 
    else
      "Create #{question.test.title} question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= image_tag("#{badge.image_url}", size: "128x128") %></td>
  <td><%= t(badge.rule) %> <%= badge.option %></td>
  <td><%= link_to 'Изменить', edit_admin_badge_path(badge)  %></td>
  <td><%= link_to 'Удалить',
                  admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: 'Вы уверены?'}%>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :name, 'Название:' %><br>
  	<%= form.text_field :name %>
  </p>

  <p>
  	<%= form.label :image_url, 'Ссылка на изображение:' %><br>
  	<%= form.text_field :image_url %>
  </p>

  <p>
    <%= form.label :rule, 'Примеры правил:' %><br>
    <%= form.select :rule, Badge::TYPES_OF_BADGES.map { |type| [ t(type), type ] }, prompt: true %>
  </p>

  <p>
  	<%= form.label :option, 'Критерии:' %><br>
  	<%= form.text_field :option %>
  </p>

  <p>
    <%= image_tag("#{@badge.image_url}", size: "128x128") if @badge.image_url.present? %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Изменить бэйдж <%= @badge.name %></h1>

<%= render 'form' %>
<%= link_to 'Назад', admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>Список бэйджей</h1>
<p>
  <%= link_to 'Создать бэйдж', new_admin_badge_path %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class='table'>
  <tr>
  	<th>Название</th>
  	<th>Бэйдж</th>
  	<th>Правило</th>
  	<th colspan = '2'>Возможные действия</th>
  </tr>
  <%= render @badges %>
</table>

<%= link_to 'Назад', admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1>Создать новый бэйдж</h1>

<%= render 'form' %>
<%= link_to 'Назад', admin_badges_path %>

app/views/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= image_tag("#{badge.image_url}", size: "128x128") %></td>
  <td><%= t(badge.rule) %> <%= badge.option %></td>
<tr>

app/views/badges/_user_badges.html.erb
<tr>
  <td><%= user_badge.name %></td>
  <td><%= image_tag("#{user_badge.image_url}", size: "128x128") %></td>
  <td><%= t(user_badge.rule)%> <%= user_badge.option %></td>
</tr>

app/views/badges/index.html.erb
<% if @user_badges.present? %>
  <h1>Ваши бэйджи</h1>

  <table class='table'>
  	<tr>
  	  <th>Название</th>	
  	  <th>Бэйдж</th>
  	</tr>
  	<%= render partial: 'user_badges', collection: @user_badges, as: :user_badge %>
  </table>
<% else %>
  <p><% flash[:notice] = t('no_badges')%></p>
<% end %>

<h1>Все бэйджи</h1>

<table class='table'>
  <tr>
  	<th>Название</th>	
  	<th>Бэйдж</th>
  </tr>
  <%= render @badges %>
</table>

<%= link_to 'Назад', tests_path %>