config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {sessions: 'sessions'}

  resources :badges, only: :index

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end    
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers_amount, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers_amount
    errors.add(:amount) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  TYPES_OF_BADGES = %i[all_by_category first_try all_by_level]

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image_url, :rule, presence: true
  validates :name, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', optional: true

  has_many :questions, dependent: :destroy

  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  
  scope :by_category, -> (title) {
   joins(:category)
   .where(categories: {title: title})
   .order(title: :desc) }

  def self.select_title(title)
    by_category(title).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions +=1 if correct_answer?(answer_ids)
    save!
  end

  def passed_by_percents
    ((correct_questions.to_f * 100) / test.questions.count).round(0)
  end

  def passed?
    passed_by_percents.to_i >= SUCCESS_RATIO
  end

  def left_time
    return if test.timer.nil?
    time = set_timer - Time.current
    return 0 if time <= 0
    time
  end

  def time_is_over?
    left_time == 0
  end

  private
  
  def set_timer
    created_at + test.timer.minute
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_current_question
    return unless test.present?
    self.current_question = 
      if current_question.nil?
        test.questions.first
      else
        next_question
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  def show_passed_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/alert_helper.rb
module AlertHelper

  def add_alert_message(key)
    case key.to_sym
      when :alert
        "alert-danger"
      when :warning
        "alert-warning"
      when :notice
        "alert-success"
      else
        "alert-info"
    end  
  end  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted? 
      "Edit #{question.test.title} question" 
    else
      "Create #{question.test.title} question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-primary row">
  <div class="container">
    <span class="navbar-brand">
      <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
      <%= link_to 'Бэйджи', admin_badges_path, class: "btn btn-sm btn-secondary"  %>
      <%= link_to 'All Gists', admin_gists_path, class: "btn btn-sm btn-secondary" %>
    </span>
    
    <span class="navbar-brand">
      <%= link_to t('.adminpanel'), admin_tests_path, class: 'navbar-brand' %>
    </span>

    <span class="navbar-text">
      <% if user_signed_in? %>
        Welcome, <b><%= current_user.email %></b> Guru |
        <%= link_to link_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-sm btn-primary" %>
      <% else %>
        <%= link_to t('.login'), new_session_path(resource_name) %> |
        <%= link_to t('.signin'), new_registration_path(resource_name) %>
      <% end %>
    </span>
  </div>
</nav>  

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <hr>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  <div>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, class: "alert #{add_alert_message(key)}", role: "alert" %>
<% end %>

app/views/shared/_footer.en.html.erb
<small>
  <% if current_user %>
    <p>
      <%= link_to 'Feedback', new_feedback_path %>
    </p>
  <% end %>
  <%= current_year %>  produced by Stanislav Ilchenko.
  <%= github_url("Stanislav109", "TestGuru") %>.
  These are the TESTS that the user can pass.
  This is the study project of online school
  <%= link_to "Thinknetica", "http://thinknetica.com", target: '_blank' %>
</small>.

app/views/shared/_footer.html.erb
<small>
  <%= current_year %>  produced by Stanislav Ilchenko.
  <%= github_url("Stanislav109", "TestGuru") %>.
  These are the TESTS that the user can pass.
  This is the study project of online school
  <%= link_to "Thinknetica", "http://thinknetica.com", target: '_blank' %>
</small>

app/views/shared/_footer.ru.html.erb
<small>
  <% if current_user %>
    <p>
      <%= link_to 'Обратная связь', new_feedback_path %>
    </p>
  <% end %>
  <%= current_year %>  создатель проекта Станислав Ильченко
  <%= github_url("Stanislav109", "TestGuru") %>.
  Проект TestGuru - это набор тестов, с возможностью их проходить.
  Проект разработан в процессе обучения в онлайн-школе
  <%= link_to "Thinknetica", "http://thinknetica.com", target: '_blank' %>.
</small>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
  <p class="nav user">
    Welcome, <b><%= current_user.email %></b>, Guru |
  <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </p>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <% if current_user.is_a?(Admin) %>
    <%= link_to t('.adminpanel'), admin_tests_path %>
    <%= link_to 'All Gists', admin_gists_path, class: "btn btn-sm btn-secondary" %>
  <% end %>

  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if user_signed_in? %>
    <%= link_to 'Бэйджи', badges_path, class: "btn btn-sm btn-secondary" %> |
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.login'), new_session_path(resource_name) %> |
      <%= link_to t('.signin'), new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>  