config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {sessions: 'sessions'}

  resources :badges, only: :index

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end    
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers_amount, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers_amount
    errors.add(:amount) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  TYPES_OF_BADGES = %i[all_by_category first_try all_by_level]

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image_url, :rule, presence: true
  validates :name, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', optional: true

  has_many :questions, dependent: :destroy

  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  
  scope :by_category, -> (title) {
   joins(:category)
   .where(categories: {title: title})
   .order(title: :desc) }

  def self.select_title(title)
    by_category(title).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions +=1 if correct_answer?(answer_ids)
    save!
  end

  def passed_by_percents
    ((correct_questions.to_f * 100) / test.questions.count).round(0)
  end

  def passed?
    passed_by_percents.to_i >= SUCCESS_RATIO
  end

  def left_time
    return if test.timer.nil?
    time = set_timer - Time.current
    return 0 if time <= 0
    time
  end

  def time_is_over?
    left_time == 0
  end

  private
  
  def set_timer
    created_at + test.timer.minute
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_current_question
    return unless test.present?
    self.current_question = 
      if current_question.nil?
        test.questions.first
      else
        next_question
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  def show_passed_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create!(user: current_user, question: @test_passage.current_question, url: result.html_url, gist_id: result.id)
      flash[:notice] = t('.success', url: result.html_url)    
    else
      flash[:alert] = t('.failure')
    end
    redirect_to @test_passage
  end

  private
  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show
    if @test_passage.time_is_over?
      redirect_to result_test_passage_path(@test_passage)
    end
  end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      #TestsMailer.completed_test(@test_passage).deliver_now
      @test_passage.update!(sucess: true) if @test_passage.passed?
      prize
      redirect_to result_test_passage_path(@test_passage)
    else
      redirect_to @test_passage
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def prize
    badges = BadgeService.new(@test_passage).call
    unless badges.empty?
      current_user.badges.push(badges)
      flash[:notice] = t('add_badge')
    end
  end
end

app/helpers/alert_helper.rb
module AlertHelper

  def add_alert_message(key)
    case key.to_sym
      when :alert
        "alert-danger"
      when :warning
        "alert-warning"
      when :notice
        "alert-success"
      else
        "alert-info"
    end  
  end  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted? 
      "Edit #{question.test.title} question" 
    else
      "Create #{question.test.title} question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def current_timer(time)
    return if time.nil?
    timer = time.round
    min = timer / 60
    sec = timer % 60
    "#{min}:#{sec}"
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% unless @test_passage.left_time.nil? %>
  <% flash.now[:alert] = t('times_up') if @test_passage.left_time == 0 %>
  <% flash.now[:notice] = t('in_time') if @test_passage.left_time > 0 %>
<% end %>

<% if @test_passage.passed? %>
  <div class="correct">
    <h2> Ура! Вы прошли тест! </h2>
    <h2> <%= @test_passage.passed_by_percents %> % </h2>
  </div>
<% else %>
  <div class="wrong">
    <h2> Тест не пройден </h2>
    <h2> <%= @test_passage.passed_by_percents %> % </h2>
  </div>
<% end %>

<p><%= link_to 'To test list', root_path %></p>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> test</h1>

<h3> Question  <%= @test_passage.test.questions.ids.find_index(@test_passage.current_question.id) + 1 %> /
  <%= @test_passage.test.questions.count %> </h3>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put, id: "test_passage" do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body,
      include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object_id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <div class="progress">
  <%= tag.div class: "progress-bar", 
              data: { current_question: @test_passage.test.questions.ids.find_index(@test_passage.current_question.id) + 1, 
                      question_count: @test_passage.test.questions.count } %>
  </div>

  <p><%= link_to 'Gist Question', gists_path(test_passage_id: @test_passage.id), method: :post %></p>
  <p><%= form.submit 'Next', id: "next" %></p>
<% end %>

<% unless @test_passage.test.timer.nil? %>
  <%= tag.div current_timer(@test_passage.left_time), data: { second: @test_passage.left_time }, id: "timer-js", class: "timer" %>
<% end %>

<p><%= link_to 'To test list', root_path %></p>